debug: true

server:
  address: 127.0.0.1
  port: 8080
  tomcat:
    max-threads: 200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    basename: il8n/messages
    encoding: UTF-8
    cache-duration: 3600

  devtools:
    restart:
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

##指定映射文件
mybatis:
  config-location: classpath:mybatis-config.xml

file:
  upload:
    path: e:/upload/